## Where the samples will be written
save_data: data/run/example
## Where the vocab(s) will be written
src_vocab: data/run/vocab.txt
tgt_vocab: data/run/vocab.txt
# Prevent overwriting existing files in the folder
overwrite: True
share_vocab: True


# Corpus opts:
data:
    corpus_1:
        path_src: data/train.src
        path_tgt: data/train.tgt
    valid:
        path_src: data/valid.src
        path_tgt: data/valid.tgt

# Vocabulary files that were just created
src_vocab: data/run/vocab.txt
tgt_vocab: data/run/vocab.txt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: ./trained_model/model_chatbot_livejupiter_copy
save_checkpoint_steps: 500
train_steps: 200000
valid_steps: 500
batch_size: 256
early_stopping: 4 
early_stopping_criteria: ppl
learning_rate: 0.5


# CopyMechanism
encoder_type: brnn
copy_attn: 'true'
global_attention: mlp
reuse_copy_attn: 'true'
bridge: 'true'